# This is a basic workflow that build and deploys the angular application
name: build and deploy

# Controls when the action will run. Triggers the workflow on push events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # Build the angular app
  build_and_deploy_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build:prod
        working-directory: matraum-app
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: ./matraum-app
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: matraum-app
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels