# This is a basic workflow that build and deploys the angular application
name: build and deploy

# Controls when the action will run. Triggers the workflow on push events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # Build the angular app
  build:
    
    name: Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
       working-directory: ./matraum-app
       
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2
      
      # install Node (version should be the same as local, i.g. 14.x)
      - name: Use Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
        
        # installs all npm dependecies
      - name: Install dependencies
        run: npm ci
        
        # builds the angular app (prod version)
      - name: Build
        run: npm run build -- --prod
   
        # saves the build mock_data in an artifact
      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_dist
          path: ./matraum-app/dist/matraum-app
          
  # deploy the app via FTP
  FTP-Deploy-Action:
    name: Deploy via FTP
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
   
    # download the build mock_data form job 1
    - name: Download build
      uses: actions/download-artifact@v1
      with:
       name: deploy_dist     
       path: './dist'   
              
    # upload via ftp
    - name: Upload ftp
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ftp://ftp.zh11.ch
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "dist"
